name = "oj-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = ""

[[d1_databases]]
binding = "DB"
database_name = "oj-database"
database_id = ""

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"

[[send_email]]
name = "SEND_EMAIL"

[vars]
GITHUB_CLIENT_ID = ""
GITHUB_CLIENT_SECRET = ""
GITHUB_TOKEN = ""
CPOAUTH_CLIENT_ID = ""
CPOAUTH_CLIENT_SECRET = ""
CALLBACK_SECRET = ""
JWT_SECRET = "your secret"
JUDGE_REPO = "your-username/oj-judge"
FRONTEND_URL = "https://your-frontend-url"
REGISTRATION_OPEN = "true"
DEFAULT_FROM_EMAIL = "noreply@your-domain.com"
